export const URL = "http://127.0.0.1:8000/";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADEDAUTH_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

export const RESET_PASSWORD_CONRIM_SUCCESS = "RESET_PASSWORD_CONRIM_SUCCESS";
export const RESET_PASSWORD_CONRIM_FAILED = "RESET_PASSWORD_CONRIM_FAILED";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
